services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: irrigasmart-frontend
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - irrigasmart-network

networks:
  irrigasmart-network:
    driver: bridge

volumes:
  mysql_data:
